import { createFileRoute } from "@tanstack/react-router";
import { LegalPage } from "@/components/site/LegalPage";
import { seo } from "@/components/site/blocks";

export const Route = createFileRoute("/privacidad")({
  head: () => ({ meta: seo("Política de Privacidad | NATXAJO CORPORATION", "Política de privacidad y tratamiento de datos de NATXAJO CORPORATION.") }),
  component: () => <LegalPage title="Política de Privacidad" sections={[
    { title: "Responsable del tratamiento", paragraphs: ["NATXAJO CORPORATION gestiona los datos personales facilitados a través de su sitio institucional, sus formularios y su portal corporativo para atender consultas y administrar las cuentas. Puede dirigir solicitudes sobre el tratamiento de sus datos a natxajosupport@gmail.com o mediante el formulario de contacto, indicando el motivo de su solicitud.", "El acceso a la información se limita al titular de la cuenta y al personal autorizado según sus funciones. El alojamiento, la autenticación y el almacenamiento de la plataforma se apoyan en Lovable Cloud. El sitio carga tipografías desde Google Fonts; esa solicitud transmite información técnica de conexión al servicio, sin incluir el contenido de los formularios."] },
    { title: "Datos recopilados", paragraphs: ["El formulario de contacto solicita nombre, apellido, correo electrónico, área de interés, asunto y mensaje. Empresa, teléfono y país son campos opcionales. Cada consulta se registra con un identificador, fechas y estado para facilitar su gestión y seguimiento.", "Las cuentas incluyen los datos de identificación y de perfil proporcionados por el usuario, el estado de verificación del correo y los permisos de acceso. El servicio de autenticación gestiona las credenciales; las contraseñas no se incorporan a las consultas ni a los registros administrativos.", "Para proteger la plataforma se registran eventos de seguridad, fechas, una descripción resumida del navegador y un identificador derivado de la dirección IP. Los registros no deben incluir contraseñas, códigos de verificación ni tokens de acceso. Evite remitir datos sensibles o información de terceros que no sea necesaria para atender su requerimiento."] },
    { title: "Finalidad", paragraphs: ["Los datos se utilizan para recibir, clasificar y atender consultas; mantener las cuentas y el perfil; permitir el seguimiento de las solicitudes; administrar los permisos; y prevenir usos abusivos o accesos no autorizados. El formulario requiere la aceptación expresa del tratamiento de datos para gestionar la consulta. No es necesario crear una cuenta para enviarla.", "Las comunicaciones de cuenta, recuperación de acceso y seguridad se vinculan a acciones o incidencias concretas. Los datos de contacto no se destinan mediante esta plataforma a campañas publicitarias ni a envíos masivos. Los avisos administrativos adicionales por correo solo se habilitarán cuando exista una configuración de envío válida; el registro de las consultas no depende de esa habilitación.", "Los datos se conservarán durante el tiempo necesario para atender su finalidad y las obligaciones que resulten aplicables, sin establecer un plazo legal no verificado. La eliminación de una cuenta y la gestión de los registros de consultas son procesos distintos: los datos identificativos podrán anonimizarse y los registros restantes deberán revisarse conforme a su finalidad y a los derechos del interesado."] },
    { title: "Derechos del usuario", paragraphs: ["Puede solicitar información sobre sus datos, su acceso, rectificación o eliminación y, cuando resulte aplicable, la limitación u oposición al tratamiento y la portabilidad. También puede retirar el consentimiento otorgado, sin afectar al tratamiento realizado previamente de forma válida. El alcance de cada derecho depende de la legislación aplicable y de las circunstancias de la solicitud.", "El portal permite actualizar los datos de perfil y solicitar la eliminación de la cuenta mediante las comprobaciones de seguridad previstas. Para otros requerimientos, contacte con natxajosupport@gmail.com e indique los datos mínimos que permitan identificar la solicitud. Nunca envíe contraseñas ni códigos de acceso. Antes de facilitar o modificar información personal, podrá requerirse una comprobación proporcionada de identidad."] },
  ]} />,
});
