import { createFileRoute } from "@tanstack/react-router";
import { LegalPage } from "@/components/site/LegalPage";
import { seo } from "@/components/site/blocks";

export const Route = createFileRoute("/terminos")({
  head: () => ({ meta: seo("Términos de Uso | NATXAJO CORPORATION", "Términos y condiciones de uso del sitio web de NATXAJO CORPORATION.") }),
  component: () => <LegalPage title="Términos de Uso" sections={[
    { title: "Objeto", paragraphs: ["Estos términos regulan el acceso al sitio institucional de NATXAJO CORPORATION, el envío de consultas y el uso de las cuentas y del portal corporativo. La plataforma presenta las áreas de actividad de la corporación y permite canalizar requerimientos hacia el ámbito especializado correspondiente.", "La información publicada tiene carácter institucional. El envío de una consulta, la creación de una cuenta o el acceso al portal no constituyen por sí mismos una contratación, una aceptación de proyecto ni un compromiso de prestación de servicios. El alcance de cualquier relación comercial deberá acordarse expresamente."] },
    { title: "Uso del sitio", paragraphs: ["El usuario debe facilitar información veraz y pertinente, mantener sus credenciales bajo su control y utilizar la plataforma de manera lícita. No debe compartir contraseñas ni códigos de verificación, suplantar identidades, acceder a información ajena o intentar eludir las restricciones de seguridad.", "Se prohíbe enviar contenido malicioso, solicitudes automatizadas abusivas o información obtenida sin autorización. No incluya contraseñas, documentos de identidad ni datos sensibles innecesarios en las consultas. NATXAJO CORPORATION podrá restringir el acceso ante usos indebidos o riesgos de seguridad, sin perjuicio de los derechos que correspondan al usuario."] },
    { title: "Propiedad intelectual", paragraphs: ["La denominación NATXAJO CORPORATION, sus elementos de identidad visual y los contenidos propios del sitio están destinados a identificar y comunicar la actividad corporativa. Su publicación no concede una licencia para utilizarlos como marca propia, atribuirse una relación con la corporación o reproducirlos con fines comerciales sin autorización.", "Los derechos sobre materiales de terceros, cuando existan, corresponden a sus respectivos titulares. Los usuarios conservan los derechos sobre la información que remitan y deben contar con autorización para compartirla. Los usos permitidos por la legislación aplicable no quedan limitados por estos términos."] },
    { title: "Limitación de responsabilidad", paragraphs: ["NATXAJO CORPORATION procura que la información institucional sea clara y pertinente. No obstante, los contenidos pueden actualizarse y no sustituyen una evaluación técnica, contractual o profesional específica. La disponibilidad del sitio puede verse afectada por mantenimiento, incidencias técnicas o circunstancias ajenas al control de la corporación.", "La plataforma aplica medidas de protección, pero ningún sistema puede garantizar la ausencia absoluta de interrupciones o incidentes. La responsabilidad se determinará conforme a las obligaciones efectivamente asumidas y a la legislación aplicable. Estos términos no excluyen responsabilidades ni derechos que no puedan limitarse legalmente."] },
  ]} />,
});
